### ISSUE TITLE
Clicking on Dropdown set to mouseover closes it

### ISSUE THREAD

**Issue by kaladay** [TAMULib/weaver-components#124]
This seems a bit unexpected because while clicking on the hover over area will close it, clicking on it again after it closes in this way will not open. (That second part is correct because its set to mouseover instead of click.)

This also applies to clicking anywhere inside the opened dropdown.
Clicking on a mouseover dropdown (the dropped down part) closes the entire dropdown.

**Comment by jeremythuff** [comment]
I think the current build this not the case. I was unable to reproduce here: https://tamulib.github.io/weaver-components/docs/usage/#WeaverDropdownButtonStyles
