### ISSUE TITLE
Weaver Components should have an element query strategy

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/weaver-components#27]

**Comment by jeremythuff** [comment]
This might be working currently, this should be verified.

**Comment by jeremythuff** [comment]
Angular provides a `@ViewChild` and `@ContentChild` which can be used for this purpose

**Comment by wwelling** [comment]
But do they work as expected with Angular Elements. I am pretty sure we went at lengths to try and get this to work using those decorators. I recall a branch that had a proposed solution.
