### ISSUE TITLE
Weaver Components should use an alternate mechanism to `display: none` when components are ready

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/weaver-components#363]
Currently, both our weaver and weaver-component apps remove display none after they are loaded. We want to utilize class rules instead.

Example:
```
.wvr-components-display {
  display: none;
}
```

Once each framework loads they will remove these classes from the body.

- [x] Directory
- [x] Subject Librarian 
- [x] Magpie
- [x] Sage
- [x] Cascade (Michael)

* create issue on angularjs to mimic this functionality

**Comment by kaladay** [comment]
Directory UI has the following issue, which is now updated:
- TAMULib/DirectoryUI/issues/232

**Comment by kaladay** [comment]
The following issues have been created in regards to this:

- TAMULib/SubjectLibrarianUI/issues/73
- TAMULib/MetadataAssignmentToolUI/issues/187
- TAMULib/SAGE/issues/348
