### ISSUE TITLE
Investigate and solve the performance problem of loading a large number of components at one time. 

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/weaver-components#461]
This is observed in ng-repeat of 255 elements via directoryappui. It would be great to isolate this problem outside of angularjs to better determine the causes of the performance degradation.

This issue appears to be made worse when the component being loaded is over a certain threshold of complexity.

**Comment by kaladay** [comment]
Created Issue from this investigation:
- https://github.com/TAMULib/weaver-components/issues/480
