### ISSUE TITLE
Automatically test Components PRs with https://github.com/marketplace/axe-linter

### ISSUE THREAD

**Issue by jcreel** [TAMULib/weaver-components#487]
Activate this on weaver-components and tl-components.
Configure, to extent possible, to check in accordance with TAMU policies: https://itaccessibility.tamu.edu/laws_policies_standards/web_standards.php

**Comment by kaladay** [comment]
A manual process of using Axe is now described here:
- https://github.com/TAMULib/weaver-components/wiki/Accessibility-Scanning
- https://github.com/TAMULib/tamu-library-components/wiki/Accessibility-Scanning

**Comment by kaladay** [comment]
The Axe-Linter seems like it might be a dead project.
The URL is: https://axe-linter.deque.com/
Which returns Cannot GET /.
The internet Archive shows that it has been "under maintenance" and I could not find an archive not under maintenance until some random time in 2020.

The [dequelabs github](https://github.com/dequelabs) seems active.

Their website at a different URL appears to work:
https://www.deque.com/axe/linters/

The linter originally linked in the issue on the marketplace says that it is free for **personal use only** and does not provide a way to use it within an Organization.

Their [Terms of Service](https://www.deque.com/axe/axe-for-web/axe-pro-beta-license-agreement/) (found within https://github.com/marketplace/axe-linter) goes to a 404.
