### ISSUE TITLE
Weaver Components load slowly in IE 11

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/weaver-components#56]
When loading in IE11 the weaver components take a significantly longer period of time to render, as opposed to all other major browsers.

The first suspect for this behavior is the css-elemnt-query library.

**Comment by kaladay** [comment]
This issue might not be relevant anymore:
- https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/

Summary: Internet Explorer 11 is retired and is no longer supported.

**Comment by kaladay** [comment]
https://www.tamu.edu/statements/browsers.html
